# Generated by Django 5.2.8 on 2025-11-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwh', models.FloatField()),
                ('rango', models.CharField(max_length=20)),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
