# Generated by Django 5.2.8 on 2025-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_energia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenergia',
            name='mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
