# Generated by Django 5.2.8 on 2025-11-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_energia', '0002_registroenergia_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenergia',
            name='semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
